// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHYwz4Zto-dAagVGpAo-kEyU655eYKxBA',
    appId: '1:495205958719:web:5551b712d1637c66d4a48a',
    messagingSenderId: '495205958719',
    projectId: 'saloon-app-a9691',
    authDomain: 'saloon-app-a9691.firebaseapp.com',
    storageBucket: 'saloon-app-a9691.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq9r7FwCKyH_4JnkOFysfS0Yri7DAnr6k',
    appId: '1:495205958719:android:1a53ef0133fe6988d4a48a',
    messagingSenderId: '495205958719',
    projectId: 'saloon-app-a9691',
    storageBucket: 'saloon-app-a9691.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeNT4-WeKhl2qfMw2zosff52ouBaiIOb4',
    appId: '1:495205958719:ios:a53a2c79fa773bdad4a48a',
    messagingSenderId: '495205958719',
    projectId: 'saloon-app-a9691',
    storageBucket: 'saloon-app-a9691.firebasestorage.app',
    iosBundleId: 'com.example.saloonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeNT4-WeKhl2qfMw2zosff52ouBaiIOb4',
    appId: '1:495205958719:ios:a53a2c79fa773bdad4a48a',
    messagingSenderId: '495205958719',
    projectId: 'saloon-app-a9691',
    storageBucket: 'saloon-app-a9691.firebasestorage.app',
    iosBundleId: 'com.example.saloonApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHYwz4Zto-dAagVGpAo-kEyU655eYKxBA',
    appId: '1:495205958719:web:a2f811745adb3220d4a48a',
    messagingSenderId: '495205958719',
    projectId: 'saloon-app-a9691',
    authDomain: 'saloon-app-a9691.firebaseapp.com',
    storageBucket: 'saloon-app-a9691.firebasestorage.app',
  );
}
